version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/openjdk:11.0-browsers
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: chmod +x ./gradlew
      - run: ./gradlew dependencies
      - run: xvfb-run -a ./gradlew check --stacktrace
      - run: ./gradlew jacocoTestReport

      - run: "[[ -n ${SIGNING_KEY_SECRING_BASE64} ]]"
      - run: echo $SIGNING_KEY_SECRING_BASE64 | base64 --decode > ./signing.key.secring
      - run: echo "export SIGNING_KEY_PATH=./signing.key.secring" >> "$BASH_ENV"
      - run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository -DDEPLOYMENT=true

      - run: mkdir -p projectpage
      - run: cp -rv build/reports/* projectpage
      - run: cp -rv build/docs/* projectpage
      - run: cp -rv docs/* projectpage
      # force push to the repo gh-pages branch

  build:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: chmod +x ./gradlew
      - run: ./gradlew dependencies
      - run: xvfb-run -a ./gradlew check --stacktrace

workflows:
  build-and-deploy-workflow:
    jobs:
      - build-and-deploy:
          filters:
            tags:
              # any tag
              only: /.*/
            branches:
              # no branches
              ignore: /.*/

  build-workflow:
    jobs:
      - build:
          filters:
            tags:
              # not tag
              ignore: /.*/
